title: Jonas Giehl
description: Software e Tecnologia
google_analytics: UA-56317011-1
show_downloads: false
remote_theme: "mmistakes/so-simple-theme"
locale: "pt-br"
read_time: true
words_per_minute: 200
date_format: "%d-%m-%Y"
mathjax: true

twitter:
  username: jonasgiehl # site's Twitter username

# Build settings
markdown: kramdown
feed:
  path: atom.xml
  
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomoy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

gems:
gem "github-pages", group: :jekyll_plugins

plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

  # Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: false
      share: true
	  
  
  # Site Author
author:
  name: Jonas Giehl
  # picture: /images/michael-rose-photo.jpg
  email: jonas@giehl.com.br
  twitter: ichbineingiehl
  links:
    - title: Twitter
      url: https://twitter.com/ichbineingiehl
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/jonasgiehl
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/jonasgiehl
      icon: fab fa-github-square
	  
	  
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/ichbineingiehl
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/jonasgiehl
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/jonasgiehl
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square	  