title: Jonas Giehl
description: Software e Tecnologia
google_analytics: UA-56317011-1
show_downloads: false
remote_theme: "mmistakes/so-simple-theme"

gems:
gem "github-pages", group: :jekyll_plugins

